name: Branch-based GitHub Pages Deployment

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: |
          BRANCH=${{ github.ref_name }}
          mkdir -p build/$BRANCH
          npx browserify web/main.js -t brfs | npx terser -c -m -o build/$BRANCH/static/bundle.min.js
          cp -r dist/* build/$BRANCH

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
