name: Versioned GitHub Pages Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: |
          VERSION=${{ github.event.inputs.version }}
          mkdir -p build/$VERSION
          npm run build:prod
          cp -r dist/* build/$VERSION

          # Create root index.html that redirects to the current version, preserving socketURL parameter if present
          cat > build/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <script>
              // Get socketURL parameter if present
              const urlParams = new URLSearchParams(window.location.search);
              const socketURL = urlParams.get('socketURL');
              
              // Build redirect URL
              let redirectUrl = '${VERSION}/';
              if (socketURL) {
                redirectUrl += '?socketURL=' + encodeURIComponent(socketURL);
              }
              
              // Redirect immediately
              window.location.href = redirectUrl;
            </script>
            <meta http-equiv="refresh" content="0; url=${VERSION}/">
          </head>
          <body>
            Redirecting to latest version...
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
